<?php

namespace AppBundle\Repository;

/**
 * MapLayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapLayerRepository extends \Doctrine\ORM\EntityRepository
{
}
