<?php

namespace AppBundle\Repository;

/**
 * MapPointSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapPointSetRepository extends \Doctrine\ORM\EntityRepository
{
}
