<?php

namespace AppBundle\Repository;

/**
 * YieldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YieldsRepository extends \Doctrine\ORM\EntityRepository
{
}
