<?php
/**
 * Created by PhpStorm.
 * User: jmac
 * Date: 12/28/15
 * Time: 1:28 PM
 */

namespace AppBundle\Form;


use AppBundle\Entity\MapLayer;
use AppBundle\Entity\MapPointSet;
use AppBundle\ValueObject\MapLayersUpdate;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class MapLayersType extends AbstractType
{

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('mapLayers', CollectionType::class, [
                'entry_type' => MapLayerType::class,
                'entry_options' => [
                    'required' => true
                ],
                'allow_add' => true
            ])
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults([
            'data_class' => MapLayersUpdate::class
        ]); // TODO: Change the autogenerated stub
    }

    public function getName()
    {
        return 'map_layers';
    }


}